public class W_WorkflowHomeConstant {
  	//申請部署
    public String sinseibu{get;set;}
    //record id
    public String sinseiId{get;set;}
    //申請名
    public String sinseimei{get;set;}
    //申請日
    public String sinseibi{get;set;}
    //申請状況
    public String sinseistatus{get;set;}
    //承認者
    public String admit{get;set;} 
    
    public static final  String AppropriateAppointedAppTable='AppropriateAppointedApp__c';
    public static final  String JoinAppFormPPDDownloadTable='JoinAppFormPPDDownload__c';
    public static final  String ShiftDutySystemApplTable='ShiftDutySystemAppl__c';
    public static final  String FlexWorkPlanApplTable='FlexWorkPlanAppl__c';
    public static final  String HomeWorkAppointedApplTable='HomeWorkAppointedAppl__c';
    public static final  String DonationApplicationTable='DonationApplication__c';
    public static final  String PoliFoundPartyTicketPurchaseApplTable='PoliFoundPartyTicketPurchaseAppl__c';
    public static final  String DuesApplicationTable='DuesApplication__c';
    public static final  String LayoutChangeApplTable='LayoutChangeAppl__c';

}